# Generated by Django 3.2.6 on 2021-08-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='timestamp',
        ),
    ]
